enum Emoji {
    // פרצופים
    like = '👍',
    heart = '❤',
    smile = '😊',
    rocket = '🚀',
    star = '⭐',
    fire = '🔥',
    clap = '👏',
    thumbsDown = '👎',
    party = '🎉',
    crying = '😢',
    laughing = '😂',
    wink = '😉',
    thinking = '🤔',
    sleeping = '😴',
    astonished = '😲',
    angry = '😠',
    surprised = '😮',
    dizzy = '😵',
    cool = '😎',
    kissing = '😘',
    flushed = '😳',
    nervous = '😬',

    // סמלים
    checkmark = '✅',
    crossmark = '❌',
    warning = '⚠️',
    question = '❓',
    exclamation = '❗',
    infinity = '♾️',
    recycle = '♻️',
    stopSign = '🛑',
    lock = '🔒',
    unlock = '🔓',
    magnet = '🧲',
    umbrella = '☂️',
    hourglass = '⏳',
    scissors = '✂️',
    key = '🔑',
    lightbulb = '💡',
    bomb = '💣',
    skull = '💀',
    rainbow = '🌈',

    // חיות
    cat = '🐱',
    dog = '🐶',
    mouse = '🐭',
    rabbit = '🐰',
    lion = '🦁',
    monkey = '🐵',
    panda = '🐼',
    penguin = '🐧',
    elephant = '🐘',
    tiger = '🐯',
    unicorn = '🦄',
    dragon = '🐉',
    frog = '🐸',
    fox = '🦊',

    // מזג אוויר
    sun = '☀️',
    moon = '🌙',
    cloud = '☁️',
    snowflake = '❄️',
    thunder = '⚡',
    tornado = '🌪️',
    umbrellaRain = '☔',
    raindrop = '💧',

    // תחבורה
    airplane = '✈️',
    car = '🚗',
    bus = '🚌',
    train = '🚆',
    ship = '🚢',
    bicycle = '🚲',
    trafficLight = '🚦',

    // אוכל ושתייה
    pizza = '🍕',
    burger = '🍔',
    fries = '🍟',
    iceCream = '🍦',
    coffee = '☕',
    tea = '🍵',
    cake = '🎂',
    chocolate = '🍫',
    apple = '🍎',
    watermelon = '🍉',
    lemon = '🍋',
    grape = '🍇',
    carrot = '🥕',

    // ספורט ופעילות
    soccer = '⚽',
    basketball = '🏀',
    baseball = '⚾',
    tennis = '🎾',
    golf = '🏌️',
    medal = '🏅',
    trophy = '🏆',
    boxingGlove = '🥊',
    snowboard = '🏂',
    swimming = '🏊',

    // חפצים ודברים נוספים
    book = '📚',
    laptop = '💻',
    phone = '📱',
    camera = '📷',
    gift = '🎁',
    clock = '⏰',
    anchor = '⚓',
    shoppingBag = '🛍️',
    musicalNote = '🎵',
    moneyBag = '💰',
    briefcase = '💼',
    hammer = '🔨',
    wrench = '🔧',
    globe = '🌍',
    crown = '👑',
    balloon = '🎈',
    megaphone = '📣',
    handshake = '🤝',
    wave = '👋',
    pray = '🙏',
    muscle = '💪',
}

export default Emoji